service: urban-growth

provider:
  name: aws
  region: us-west-2
  runtime: python3.6
  stage: test

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - s3:GetObject
     Resource:
       - "arn:aws:s3:::landsat-pds/*"
  -  Effect: "Allow"
     Action:
       - s3:*
     Resource:
       - "arn:aws:s3:::urban-growth/*"
  -  Effect: "Allow"
     Action:
       - sqs:ReceiveMessage
       - sqs:SendMessage
       - sqs:SendMessageBatch
       - sqs:DeleteMessage
       - sqs:GetQueueAttributes
       - logs:CreateLogGroup
       - logs:CreateLogStream
       - logs:PutLogEvents
     Resource:
       - "arn:aws:sqs:::"
       - "arn:aws:logs:::"
  -  Effect: "Allow"
     Action:
       - dynamodb:*
     Resource:
       - "arn:aws:dynamodb:::table/*"

package:
  artifact: package.zip

functions:
  get-scenes:
    handler: handler.get_scenes
    memorySize: 128
    timeout: 30
  calc-urban-score:
    handler: handler.calc_urban_score
    memorySize: 512
    timeout: 60
  get-scenes-send-queues:
    handler: handler.get_scenes_send_queues
    memorySize: 192
    timeout: 30
